### ISSUE TITLE
How do I install this plug in?

### ISSUE THREAD

**Issue by mbiddle-bcodmo** [ioos/cc-plugin-ncei#36]
Not necessarily an issue, but a note to update the documentation.
I tried to follow installation step 2. 
> Install the plugin:
> pip install 'git+git://github.com/ioos/cc-plugin-ncei.git'

```
>pip install 'git+git://github.com/ioos/cc-plugin-ncei.git'
Invalid requirement: ''git+git://github.com/ioos/cc-plugin-ncei.git''
Traceback (most recent call last):
  File "c:\users\mbiddle\appdata\local\continuum\anaconda\lib\site-packages\pip\req\req_install.py", line 82, in __init__
    req = Requirement(req)
  File "c:\users\mbiddle\appdata\local\continuum\anaconda\lib\site-packages\pip\_vendor\packaging\requirements.py", line 96, in __in
it__
    requirement_string[e.loc:e.loc + 8]))
InvalidRequirement: Invalid requirement, parse error at ""'git+git""
```
Was able to install it using the following:
```
>pip install cc-plugin-ncei
Collecting cc-plugin-ncei
  Downloading cc-plugin-ncei-2.0.1.tar.gz (90kB)
    100% |################################| 92kB 280kB/s
Requirement already satisfied: compliance-checker>=2.2.0 in c:\users\mbiddle\appdata\local\continuum\anaconda\lib\site-packages (fro
m cc-plugin-ncei)
Requirement already satisfied: isodate==0.5.4 in c:\users\mbiddle\appdata\local\continuum\anaconda\lib\site-packages (from cc-plugin
-ncei)
Requirement already satisfied: OWSLib>=0.8.3 in c:\users\mbiddle\appdata\local\continuum\anaconda\lib\site-packages (from compliance
-checker>=2.2.0->cc-plugin-ncei)
Requirement already satisfied: lxml>=3.2.1 in c:\users\mbiddle\appdata\local\continuum\anaconda\lib\site-packages (from compliance-c
hecker>=2.2.0->cc-plugin-ncei)
Requirement already satisfied: cf_units>=0.1.1 in c:\users\mbiddle\appdata\local\continuum\anaconda\lib\site-packages (from complian
ce-checker>=2.2.0->cc-plugin-ncei)
Requirement already satisfied: requests>=2.2.1 in c:\users\mbiddle\appdata\local\continuum\anaconda\lib\site-packages (from complian
ce-checker>=2.2.0->cc-plugin-ncei)
Requirement already satisfied: python-dateutil>=2.2 in c:\users\mbiddle\appdata\local\continuum\anaconda\lib\site-packages (from com
pliance-checker>=2.2.0->cc-plugin-ncei)
Requirement already satisfied: Jinja2>=2.7.3 in c:\users\mbiddle\appdata\local\continuum\anaconda\lib\site-packages (from compliance
-checker>=2.2.0->cc-plugin-ncei)
Requirement already satisfied: setuptools>=15.0 in c:\users\mbiddle\appdata\local\continuum\anaconda\lib\site-packages\setuptools-20
.6.7-py2.7.egg (from compliance-checker>=2.2.0->cc-plugin-ncei)
Requirement already satisfied: pygeoif==0.6 in c:\users\mbiddle\appdata\local\continuum\anaconda\lib\site-packages (from compliance-
checker>=2.2.0->cc-plugin-ncei)
Requirement already satisfied: netCDF4>=1.2.2 in c:\users\mbiddle\appdata\local\continuum\anaconda\lib\site-packages (from complianc
e-checker>=2.2.0->cc-plugin-ncei)
Requirement already satisfied: arrow>=0.7.0 in c:\users\mbiddle\appdata\local\continuum\anaconda\lib\site-packages (from compliance-
checker>=2.2.0->cc-plugin-ncei)
Requirement already satisfied: pytz in c:\users\mbiddle\appdata\local\continuum\anaconda\lib\site-packages (from OWSLib>=0.8.3->comp
liance-checker>=2.2.0->cc-plugin-ncei)
Requirement already satisfied: pyproj in c:\users\mbiddle\appdata\local\continuum\anaconda\lib\site-packages (from OWSLib>=0.8.3->co
mpliance-checker>=2.2.0->cc-plugin-ncei)
Requirement already satisfied: six>=1.5 in c:\users\mbiddle\appdata\local\continuum\anaconda\lib\site-packages (from python-dateutil
>=2.2->compliance-checker>=2.2.0->cc-plugin-ncei)
Requirement already satisfied: MarkupSafe in c:\users\mbiddle\appdata\local\continuum\anaconda\lib\site-packages (from Jinja2>=2.7.3
->compliance-checker>=2.2.0->cc-plugin-ncei)
Requirement already satisfied: numpy>=1.7 in c:\users\mbiddle\appdata\local\continuum\anaconda\lib\site-packages (from netCDF4>=1.2.
2->compliance-checker>=2.2.0->cc-plugin-ncei)
Building wheels for collected packages: cc-plugin-ncei
  Running setup.py bdist_wheel for cc-plugin-ncei ... done
  Stored in directory: C:\Users\mbiddle\AppData\Local\pip\Cache\wheels\c6\50\50\a31c48b690aba9da853a40d0c275864959e044d93b8d04964d
Successfully built cc-plugin-ncei
Installing collected packages: cc-plugin-ncei
Successfully installed cc-plugin-ncei-2.0.1
```

**Comment by jbosch-noaa** [comment]
@mbiddle-nodc  - Thanks for opening an issue here.

@lukecampbell  - As I have begun writing documentation for the Compliance Checker, I am interested in folding in the connection between the main checker and it's plug-ins.  I noticed the other day that the documentation for the NCEI plug-in could use some clarification.

**Comment by Bobfrat** [comment]
Just updated the README
